# Generated by Django 4.2.3 on 2023-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
