# Generated by Django 4.2.3 on 2023-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_usertable_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
