# Generated by Django 4.2.3 on 2023-09-23 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posttable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
