# Generated by Django 4.2.3 on 2023-09-24 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posttable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttable',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttable',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
