# Generated by Django 4.2.3 on 2023-09-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_posttable_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttable',
            old_name='id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='usertable',
            old_name='id',
            new_name='user_id',
        ),
    ]
